project_id = "umfrvkakvgsypqcyyzke"

[functions.send-notification]
verify_jwt = true

[functions.process-reminders]
verify_jwt = false

[functions.vapid-public-key]
verify_jwt = false

[functions.daily-preparation-reminder]
verify_jwt = false